//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDolphin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Review = new HashSet<Review>();
            this.Track = new HashSet<Track>();
        }
    
        public int albumNr { get; set; }
        public string albumName { get; set; }
        public string year { get; set; }
        public Nullable<int> artistNr { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual ICollection<Review> Review { get; set; }
        public virtual ICollection<Track> Track { get; set; }
    }
}
