//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDolphin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.Album = new HashSet<Album>();
            this.Review = new HashSet<Review>();
        }
    
        public int artistNr { get; set; }
        public string artistName { get; set; }
        public Nullable<int> companyNr { get; set; }
    
        public virtual ICollection<Album> Album { get; set; }
        public virtual RecordLabel RecordLabel { get; set; }
        public virtual ICollection<Review> Review { get; set; }
    }
}
