//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDolphin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int revNr { get; set; }
        public string date { get; set; }
        public Nullable<int> rating { get; set; }
        public string comments { get; set; }
        public Nullable<int> companyNr { get; set; }
        public Nullable<int> artistNr { get; set; }
        public Nullable<int> albumNr { get; set; }
        public Nullable<int> trackID { get; set; }
        public string username { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual RecordLabel RecordLabel { get; set; }
        public virtual Track Track { get; set; }
        public virtual User User { get; set; }
    }
}
