//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicDolphin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.Review = new HashSet<Review>();
        }
    
        public int trackID { get; set; }
        public string title { get; set; }
        public string length { get; set; }
        public string year { get; set; }
        public Nullable<int> albumNr { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual ICollection<Review> Review { get; set; }
    }
}
